### ISSUE TITLE
jam cli does not have any help

### ISSUE THREAD

**Issue by emmjohnson** [paketo-buildpacks/packit#115] opened 2021-02-11 20:44 UTC
## What happened?
jam does not have help for the commands

* What were you attempting to do?
`jam help`
`jam --help`
`jam update-builder --help`

* What did you expect to happen?
output of how to use jam and jam commands

* What was the actual behavior? Please provide log output, if possible.
```
jam update-builder
failed to execute: --builder-file is a required flag%
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by emmjohnson** [comment] 2021-02-18 17:28
I'll pick this up, cannot assign as I am not a contributor

**Comment by sophiewigmore** [comment] 2021-02-18 17:31
Closing as this is a duplicate of https://github.com/paketo-buildpacks/packit/issues/94

**Closed by sophiewigmore** 2021-02-18 17:31 UTC
Labels: good first issue
